coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        informational: true
    patch:
      default:
        target: 80%
        threshold: 1%
        informational: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

ignore:
  - "cmd/"
  - "*/mock_*.go"
  - "*/*_test.go"
